### ISSUE TITLE
Flag to print list of available compressors

### ISSUE THREAD

**Issue by flip111** [powturbo/TurboBench#20]
There is in the readme a list of compressors https://github.com/powturbo/TurboBench#compressor-lz77rolzbwtzpaq i assume these can be tested with turbobench and also that they can be specified in turbobench.ini.

I also assume that a compressor like `Intel(R) Intelligent Storage Acceleration Library` must be specified with a different name in the turbobench.ini

Could there be added a option to list all possible compressors? At first i thought `-l1` or `-l2` would print this list. But they print less entries than the 57 which can be found in the readme.

**Comment by powturbo** [comment]
I've recently removed some old or since a long time not updated codecs.
These codecs can be still manually included.
The list displays only the codecs included in the compiled turbobench.
Some codecs (not notable) must be manually downloaded into the turbobench directory.
An activation in the makefile is also necessary. 
igzip library must be first build with the ISA build tools and then linked with turbobench. 
This must be done manually (see makefile).

**Comment by flip111** [comment]
I understand, thank you for the information.
