### ISSUE TITLE
[Question] What's total difference between turbobench and lzbench?

### ISSUE THREAD

**Issue by HackToday** [powturbo/TurboBench#36]
Hi, just find this project, And not sure the really difference between turbobench and lzbench. Thanks

**Comment by powturbo** [comment]
Lzbench and turbobench are both in memory compressor benchmarks. However Turbobench offer many more features:
- A lot more codecs lz77, bwt, context mixing are supported (for ex. oodle)
- Entropy Coding codecs + other codecs
- pass codecs options as parameter (see for ex. lzma in turbobench.ini)
- Has more precision, particularly for notebooks or not very stable cpu (throttling). It pauses for 20secs after every 8 run.
- Colored output display showing pareto in compression/decompression + score (lower = better)
- Results are stored in tbb files. You can successively test and retest your codecs without loosing the past test results.
- You can use the default groups or define your own test groups in turbobench.ini. Just type the group name at the turbobench command line.
- Submodule architecture with instant updates. I'm using a script to automatically update all submodules recently changed.
  lzbench is still using very old codec versions.
- Several output formats html, markdown, text, csv,...
- many (millions) small files can be concatenated into one file and testested separately with mulibock mode.

Some old or not notable codecs are archived and no more included in the main turbobench repository., wherea lzbench 
has still abondoned or buggy codecs (ex. pitty / tornado,... ).

lzbench is more popular because it is supported by lz4 & zstd.

**Comment by HackToday** [comment]
Thanks @powturbo  for your info
